services:
  cognite:
    image: cognite/opcua-extractor-net:2.22.1
    container_name: cognite-cdf
    environment:
      - SYSTEM_HOSTNAME=${HOSTNAME} # change this to HOST if your machine has HOST as bash variable
    env_file:
      - ../cognite/.env
    restart: always
    depends_on:
      nodered:
        condition: service_healthy
        restart: true
    volumes:
      - ../cognite:/config
      - ../cognite/logs:/extractor/logs

