services:
  nodered:
    image: docker.io/nodered/node-red:3.0.1
    container_name: cognite-nodered
    hostname: ${HOSTNAME:-cognite-nodered}
    restart: always
    ports:
      - "1880:1880"
      - "4840:4840"
    volumes:
      - cognite-nodered:/data

volumes:
  cognite-nodered:

