[agent]
interval = "1s"
    round_interval = true
    metric_batch_size = 1000
    metric_buffer_limit = 10000
    collection_jitter = "0s"
    flush_interval = "10s"
    flush_jitter = "0s"
    precision = ""
    debug = true
    quiet = false
    hostname = ""
    omit_hostname = true

[[outputs.file]]
  files = ["stdout"]
  data_format = "json"

[[inputs.opcua]]
   name = "cogniteOPCUA"
   endpoint = "opc.tcp://cognite-nodered:4840"
   ## Maximum time allowed to establish a connect to the endpoint.
  connect_timeout = "60s"
  #
  ## Maximum time allowed for a request over the established connection.
  request_timeout = "60s"
  #
  ## Security policy, one of "None", "Basic128Rsa15", "Basic256",
  ## "Basic256Sha256", or "auto"
  security_policy = "None"
  #
  ## Security mode, one of "None", "Sign", "SignAndEncrypt", or "auto"
  security_mode = "None"
  #
  ## Authentication Method, one of "Certificate", "UserName", or "Anonymous".  To
  ## authenticate using a specific ID, select 'Certificate' or 'UserName'
  auth_method = "Anonymous"

  timestamp = "source"

  nodes = [ {name="testPF", namespace="1", identifier_type="s", identifier="SimPF2"} ]
  data_format = "json"

